### ISSUE TITLE
The Chimpanzee Conundrum 

### ISSUE THREAD

**Issue by wellcaffeinated** [wellcaffeinated/Tree-of-Life#18]
If you search for "chimpanzee", it will give you the option to add "Pan Troglodytes" to the tree. But you will get an error. This is where things get confusing:

I posted this as a bug here... but turns out it's not a bug in the app, it's a bug in human classification.
https://github.com/OpenTreeOfLife/feedback/issues/401

Even though "Pan Troglodytes" refer to the species classification of "Chimpanzees", it doesn't represent a specific node in the tree. There are many different species of chimpanzee, so they get classified with affixes. 

So we can search for "Western chimpanzee" or "Central chimpanzee" but searching for just "Chimpanzee" doesn't work. I'm not sure how to deal with this.

It seems that chimpanzees don't like trees ;)

**Comment by EverSalazar** [comment]
@wellcaffeinated the issue is that [Pan troglodytes (ott417950)](https://tree.opentreeoflife.org/taxonomy/browse?name=417950) (which is not on the synthetic tree) has 5 children:

1. Pan troglodytes troglodytes
2. Pan troglodytes schweinfurthii
3. Pan troglodytes verus
4. Pan troglodytes ellioti
5. Pan troglodytes vellerosus

but there's a paper that relates [Pan paniscus (ott: 158484)](https://tree.opentreeoflife.org/taxonomy/browse?id=158484) (which is not a Pan **troglodytes**) with [Pan troglodytes verus (ott752847)](https://tree.opentreeoflife.org/taxonomy/browse?id=752847)... 

If you see the tree for [Pan (ott417957)](https://tree.opentreeoflife.org/opentree/opentree9.1@ott417957/Pan) (which would be the replacement of Pan troglodytes), you'll see Pan paniscus there
![image](https://user-images.githubusercontent.com/23618796/44949344-f0092200-ae05-11e8-8cec-c8fc1fe03644.png)

So, that new classification means that Pan troglodytes cannot be a node in the tree. And also means that a species might be in the Taxonomy and have an ID, but it doesn't necessarily has a place in the synthetic tree. 

The big question is, why does the MLT search bar doesn't display [Pan (ott417957)](https://tree.opentreeoflife.org/opentree/opentree9.1@ott417957/Pan) in the results? It is capable of [correctly showing it](http://wellcaffeinated.net/Tree-of-Life/#/?ids=ott563151&ids=ott770315&ids=ott417957), but the search bar doesn't display it.

![image](https://user-images.githubusercontent.com/23618796/44949394-b258c900-ae06-11e8-88b0-f84e7e0ef673.png)

**Comment by EverSalazar** [comment]
Not sure if that explanation works, but, in short, Pan paniscus is NOT a Pan troglodytes but it is still closely related to them.

![image](https://user-images.githubusercontent.com/23618796/44949430-82f68c00-ae07-11e8-8813-99878c23ad49.png)

**Comment by wellcaffeinated** [comment]
Yes understood. It's a problem with their search... i can't backtrack to try to find actual nodes that begin with "Pan Troglodytes...", which is necessary for the app to work. That's why it fails. All it finds is the "Pan Troglodytes" entry which doesn't exist.

This is the flow of search:
Search GBIF for "chimpanzee" => get "Pan Troglodytes"
Search OTL for taxonomic name "Pan Troglodytes" => get "ott_id: 417950"
Search OTL synthetic tree for "417950" => get Error

Trying to figure out a more robust way to deal with this

**Comment by wellcaffeinated** [comment]
If you use wikidata search it works better because it'll give more specific results...

**Comment by wellcaffeinated** [comment]
I might have a solution.
At the moment I'm searching GBIF for "species". I could prioritize "subspecies" first... then you'd get the specific chimps (and other animals) at the top

I'll try it and get back to you

**Comment by wellcaffeinated** [comment]
ok it seems to work better

**Comment by wellcaffeinated** [comment]
hmm... now it's hard to search for things like snake...
