### ISSUE TITLE
Subspecies aren't always found

### ISSUE THREAD

**Issue by wellcaffeinated** [wellcaffeinated/Tree-of-Life#19]
Try searching "snake" and now most results aren't found. 

Maybe i should try filtering autocomplete results by what is possible to find on OTL

**Comment by EverSalazar** [comment]
That's weird... Is the search engine still using GBIF database? It seems that ir works for some things, but not for others. Also the duplicate issue is gone.

**Comment by EverSalazar** [comment]
Oh, I just re-read what you wrote in the Chimpanzee conundrum thread. Now I can see why a fancier search  bar would be a good idea. 

Is it possible to use OTL for searching? Seems like using other databases can be useful for some things, but in order to guarantee consistency, it might be good that the default search engine is from OTL, and then display results from other places

**Comment by EverSalazar** [comment]
I'm closing this issue, because it seems related with the [Search Engine problem](https://github.com/wellcaffeinated/Tree-of-Life/issues/20#issue-356238419).
