### ISSUE TITLE
GBIF scientific name search doesn't work

### ISSUE THREAD

**Issue by EverSalazar** [wellcaffeinated/Tree-of-Life#2]
Searching for scientific names on GBIF database doesn't work

![image](https://user-images.githubusercontent.com/23618796/44880640-6fbab380-ac83-11e8-8a8a-6af4fde56fdd.png)

**Comment by wellcaffeinated** [comment]
@EverSalazar So this is partly by design... but yes, i think it's not a good design 😅 

I'm wondering about having a more complex search. Maybe the search could have its own side menu that shows more search options.

Maybe something kind of like this...
![](https://blog.swiftype.com/app/uploads/2017/12/swiftype-website-search-ui.gif)

The left side could have toggles for different search options, and if no text is in the search it could display common animals as suggestions...

What do you think? what would be your dream search?

**Comment by EverSalazar** [comment]
That example seems nice and fancy. However, I think the important thing is that the search works for both common names and scientific names. That's the bare minimum we need. Anything else is nice, but not suuuuper necessary for now.

**Comment by EverSalazar** [comment]
Also, it would be good that we can also look for specific OTT codes directly into the search bar, or that we can write several OTT codes (separated by commas, for example), and that the app automatically add them to the tree, as a way to quickly add species to the tree.

And saying again here: maybe using Wikipedia somehow to extract the taxon identifiers is our best shot at doing the search engine. Phylogenetic databases seem to be kind of dumb and incomplete and not very friendly for laypeople. Wikipedia, on the other hand, is waaaaay better. I don't suggest Google, because search results can be tricky with brands and stuff.

Also, is it possible to use Google to search OTL database? If Google has mapped the entire OTL database, maybe we can just Google search in the OTL database

**Comment by EverSalazar** [comment]
I am closing this issue, since is more related to the [Search Engine problem](https://github.com/wellcaffeinated/Tree-of-Life/issues/20#issue-356238419).
